# Continuous Integration workflow
name: CI

# Specify when the workflow should be triggered: on push and pull_request events to the "main" branch
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

# Define environment variables to be used throughout the workflow
env:
  NODE_VERSION: '18'

# Define jobs to be executed in parallel
jobs:
  # Linting job
  lint:
    # Run this job on the latest version of Ubuntu
    runs-on: ubuntu-latest
    steps:
      # Step 1: Checkout the git repository
      - name: Checkout git repository
        uses: actions/checkout@v3

      # Step 2: Setup Node.js with the specified version and cache npm dependencies
      - name: Setup Node.js $NODE_VERSION
        uses: actions/setup-node@v3
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: 'npm'

      # Step 3: Change to the my-resto-project directory
      - name: Change to my-resto-project directory
        run: cd my-resto-project

      # Step 4: Install project dependencies
      - name: Install dependencies
        run: npm ci

      # Step 5: Perform linting checks
      - name: Linting checks
        run: npm run lint

  # Test job
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout git repository
        uses: actions/checkout@v3

      - name: Setup Node.js $NODE_VERSION
        uses: actions/setup-node@v3
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: 'npm'

      # Step 6: Change to the my-resto-project directory
      - name: Change to my-resto-project directory
        run: cd my-resto-project

      - name: Install dependencies
        run: npm ci

      # Step 7: Run tests
      - name: Test
        run: npm run test

  # Deployment job
  deploy:
    # This job depends on the successful completion of the "lint" and "test" jobs
    needs: [lint, test]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout git repository
        uses: actions/checkout@v3

      - name: Setup Node.js $NODE_VERSION
        uses: actions/setup-node@v3
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: 'npm'

      # Step 8: Change to the my-resto-project directory
      - name: Change to my-resto-project directory
        run: cd my-resto-project

      - name: Install dependencies
        run: npm ci

      # Step 9: Build the project
      - name: Build
        run: npm run build

      # Step 10: Deploy the built project to Netlify
      - name: Deploy to Netlify
        uses: nwtgck/actions-netlify@v2.0
        with:
          publish-dir: './public'
          production-branch: main
          github-token: ${{ secrets.GITHUB_TOKEN }}
          deploy-message: "Deploy from GitHub Actions"
        env:
          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
          NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}
        # Timeout for this step is set to 2 minutes
        timeout-minutes: 2
